# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "3080:3079"
#     environment:
#       - DB_USER=SA
#       - DB_PASSWORD=Ttour123
#       - DB_SERVER=localhost
#       - DB_DATABASE=model
#     depends_on:
#       - db
#   db:
#     image: mcr.microsoft.com/mssql/server:2019-latest
#     environment:
#       SA_PASSWORD: "Ttour123"
#       ACCEPT_EULA: "Y"
# #    ports:
# #      - "1434:1433" 
